// This file was generated by Prisma and assumes you have installed the following:
// pnpm add --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // `env()` từ prisma/config throw ngay khi load config nếu thiếu biến —
    // chặn cả `prisma generate` (không cần kết nối DB) khi DATABASE_URL chưa set
    // (vd `pnpm install` trong CI trước khi seed secrets). Đọc trực tiếp để
    // generate luôn chạy được; lệnh cần DB thật (migrate/seed) vẫn báo lỗi rõ
    // ràng từ Postgres nếu URL thiếu/sai.
    url: process.env.DATABASE_URL ?? "",
  },
});
